### PR TITLE
Document `__init__` methods

### PR DESCRIPTION
**Pull request by andy-faunadb**

### CODE REVIEW

**Comment by ashfire908** [comment]
Wait, what does this do?

**Comment by andy-faunadb** [comment]
Sphinx was apparently throwing away documentation of all methods named `__init__`. This should fix that.
I took the solution from: http://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method

**Comment by ashfire908** [comment]
I don't see a difference between this branch and master when I build the docs.

**Comment by ashfire908** [comment]
Never mind. I see it now. :sheep:

**Pull request merged**
