### PR TITLE
Support for Python 3

### PR DESCRIPTION
**Pull request by ashfire908**
Adds support for python 3, using future/futurize.

Superseeds #16.

### CODE REVIEW

**Comment by andy-faunadb** [comment]
Should update `index.rst` to list all supported versions.

**Comment by andy-faunadb** [comment]
Commit #50 first, then rebase this and mention in README.rst that it supports both python 2 and 3.

**Comment by ashfire908** [comment]
I've already updated the README to say that, and the merge is correctly handling the changes made by #50 as far as I can see.

**Comment by andy-faunadb** [comment]
LGTM

**Pull request merged**
