### PR TITLE
Switch to unittest asserts

### PR DESCRIPTION
**Pull request by ashfire908**
Should provide better error messages when asserts fail.

### CODE REVIEW

**Comment by andy-faunadb** [comment]
`assertDictEqual`, `assertListEqual, and `assertTupleEqual` can all be replaced by `assertEqual`, which will figure it out based on its argument's types.
See https://docs.python.org/2/library/unittest.html#unittest.TestCase.addTypeEqualityFunc

**Comment by ashfire908** [comment]
It asserts that they are equal but also of that type, but I was unaware `assertEqual` was straight up equivalent besides that bit. If we don't care to assert types, we can just switch them to `assertEqual`.

**Comment by andy-faunadb** [comment]
We're usually comparing against a literal (`self.assertDictEqual(instance["data"], {"a": 1, "b": 2})`), so asserting the type is redundant.

**Comment by ashfire908** [comment]
Yeah, I agree. I'll update it.

**Comment by andy-faunadb** [comment]
LGTM

**Pull request merged**
